--[[
    Necrosis - RETAIL DEFAULTS
    Copyright (C) - copyright file included in this release

    Default configuration values for Retail (Midnight 12.0+)
--]]

-- Define default configuration for Retail
Necrosis = Necrosis or {}
Necrosis.Config = {
	AFK = true,
	SoulshardContainer = 4,
	ShadowTranceAlert = true,
	ShowSpellTimers = true,
	AntiFearAlert = true,
	CreatureAlert = true,
	NecrosisAlphaBar = 85,
	NecrosisLockServ = true,
	NecrosisAngle = 180,
	StonePosition = {1, 2, 3, 4, 5, 6, 7, 8, 9},
	DemonSpellPosition = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
	BuffSpellPosition = {1, 2, 3, 4, 5, 6, 7, 8},
	NecrosisToolTip = true,

	MainSpell = "death_coil",
	MainSpell2 = "dark_pact",

	PetMenuPos = {x=1, y=0, direction=1},
	PetMenuDecalage = {x=1, y=49},

	BuffMenuPos = {x=0, y=1, direction=1},
	BuffMenuDecalage = {x=-65, y=18},

	CurseMenuPos = {x=1, y=0, direction=1},
	CurseMenuDecalage = {x=1, y=30},

	ChatMsg = true,
	ChatType = true,
	Language = GetLocale(),
	ShowCount = false,
	CountType = 1,
	DestroyShardwithsphere = true,
	ShadowTranceScale = 130,
	NecrosisButtonScale = 136,
	NecroisButtonRadius = 1,
	NecrosisButtonRadius = 0.95,
	NecrosisButtonSpacing = 1.1,
	NecrosisColor = "666",
	Sound = true,
	Smooth = false,
	SpellTimerPos = 1,
	SpellTimerJust = "LEFT",
	Circle = 1,
	TimerType = 1,
	SensListe = 1,
	PetName = {},
	DemonSummon = true,
	BanishScale = 100,
	Banish = true,
	NecrosisUIEnabled = true,
	deleteshards = true,
	ItemSwitchCombat = {[3] = "Pierre de soins démoniaque"},
	DestroyCount = 5,
	AutomaticMenu = false,
	ClosingMenu = true,
	BlockedMenu = false,
	PlayerSummons = true,
	PlayerSS = true,
	SteedSummon = true,
	FramePosition = {
		["NecrosisSpellTimerButton"] = {"CENTER", "UIParent", "CENTER", 100, 300},
		["NecrosisButton"] = {"CENTER", "UIParent", "CENTER", 0, -200},
		["NecrosisCreatureAlertButton_elemental"] = {"CENTER", "UIParent", "CENTER", -60, 0},
		["NecrosisCreatureAlertButton_demon"] = {"CENTER", "UIParent", "CENTER", -50, 0},
		["NecrosisAntiFearButton"] = {"CENTER", "UIParent", "CENTER", -20, 0},
		["NecrosisShadowTranceButton"] = {"CENTER", "UIParent", "CENTER", 20, 0},
		["NecrosisBacklashButton"] = {"CENTER", "UIParent", "CENTER", 60, 0},
		["NecrosisFirestoneButton"] = {"CENTER", "UIParent", "CENTER", -121,-100},
		["NecrosisSpellstoneButton"] = {"CENTER", "UIParent", "CENTER", -87,-100},
		["NecrosisHealthstoneButton"] = {"CENTER", "NecrosisMainSphere", "CENTER", -42.38417434692383, -6.71299409866333, 1.549999952316284},
		["NecrosisSoulstoneButton"] = {"CENTER", "NecrosisMainSphere", "CENTER", -38.23531723022461, 19.48186874389648, 1.549999952316284},
		["NecrosisBuffMenuButton"] = {"CENTER", "NecrosisMainSphere", "CENTER", -19.48186874389648, 38.23531723022461, 1.549999952316284},
		["NecrosisMountButton"] = {"CENTER", "NecrosisMainSphere", "CENTER", 6.71299409866333, 42.38417434692383, 1.549999952316284},
		["NecrosisPetMenuButton"] = {"CENTER", "NecrosisMainSphere", "CENTER", 30.34371948242188, 30.34371948242188, 1.549999952316284},
		["NecrosisCurseMenuButton"] = {"CENTER", "NecrosisMainSphere", "CENTER", 42.38417434692383, 6.71299409866333, 1.549999952316284},
	},

	PetShow = {true,true,true,true,true,true,true,true,true,},

	CurseShow = {true,true,true,true,true,true,true,true,},

	Timers = {
		[1] = {usage = "agony", show = true},
		[2] = {usage = "weakness", show = true},
		[3] = {usage = "elements", show = true},
		[4] = {usage = "doom", show = true},
		[5] = {usage = "tongues", show = false},
		[6] = {usage = "exhaustion", show = false},
		[7] = {usage = "corruption", show = true},
		[8] = {usage = "unstable_affliction", show = true},
		[9] = {usage = "haunt", show = true},
		[10] = {usage = "siphon_life", show = true},
		[11] = {usage = "drain_soul", show = true},
		[12] = {usage = "immolate", show = true},
		[13] = {usage = "fear", show = true},
		[14] = {usage = "howl", show = false},
		[15] = {usage = "soul_fire", show = true},
		[16] = {usage = "death_coil", show = true},
		[17] = {usage = "shadowburn", show = true},
		[18] = {usage = "fel_domination", show = false},
		[19] = {usage = "banish", show = true},
		[20] = {usage = "enslave", show = true},
		[21] = {usage = "dark_pact", show = true},
		[22] = {usage = "soulstone", show = true},
		[23] = {usage = "summoning", show = true},
		[24] = {usage = "rit_of_doom", show = false},
		[25] = {usage = "breath", show = true},
		[26] = {usage = "eye", show = false},
		[27] = {usage = "Ritual_of_Souls", show = false},
		[28] = {usage = "dark_pact", show = false},
		[29] = {usage = "inferno", show = false},
	},
}
